adds yourkit integration
democracyworks/wildfly-coreos pull request #11
Opened 2016-09-26 15:27 UTC by ddellacosta

This adds Yourkit integration into the default wildfly setup.

2016-09-26 15:31 UTC, cap10morgan requested changes
Can we move all these additions into a separate Dockerfile.yourkit that starts with a `FROM quay.io/democracyworks/wildfly:9.0.2.Final-newrelic` kind of like how we add NewRelic in the `Dockerfile.newrelic` file?

2016-09-26 15:43 UTC, ddellacosta commented
@cap10morgan Okay, part of the way there, but this is not right yet--let's check it out together when you get a chance.

2016-09-26 15:49 UTC, cap10morgan commented on Dockerfile
> +EXPOSE 9990 10001
This port should go into `Dockerfile.yourkit` too.

2016-09-26 15:54 UTC, cap10morgan requested changes

2016-09-27 16:53 UTC, ddellacosta commented on Dockerfile
> +EXPOSE 9990 10001
Okay, moved.

2016-09-30 17:06 UTC, cap10morgan approved these changes

2016-11-29 15:56 UTC, ddellacosta commented
@cap10morgan I've been slow about merging this in, but now I'm wondering if I should even bother, if we are removing wildfly entirely (?)--what do you think?

2016-11-29 16:13 UTC, cap10morgan commented
I am indeed removing WildFly as fast as I can. I say this is no longer a priority.

2016-12-15 15:48 UTC, cap10morgan commented
@ddellacosta Should we close this one w/o a merge?

2016-12-22 21:38 UTC, closed without merging